"""Pin the machine-readable support matrix (F1 contract-freeze draft §3.4,
as amended by E2's volatile mission/WP vocabulary).

``spec_kitty_events.strict.SUPPORT_MATRIX`` is the authority downstream
candidates (F2-T1, F3-T1, D1-T1, Z1-T1) pin by digest in
``declared_dependency_contracts`` to know which payload IDs / event types
this package supports. The published copy is ``support_matrix.json``
(package data, generated by ``schemas/generate.py`` under the existing
``--check`` drift gate).

30 rows total: 14 journal rows + 16 volatile rows (the Ephemeral Team Status
vocabulary — ``WPStatusChanged``, ``MissionCreated``, ``MissionClosed``,
``PhaseEntered``, the six mission-run types — plus 6 observation rows keyed
by ``(event_type="HarnessObservation", kind)``, each carrying its own
payload ID -- exactly six payload IDs, matching
``HARNESS_OBSERVATION_PAYLOAD_IDS``).
"""

from __future__ import annotations

import importlib
import json
from pathlib import Path

import pytest
from packaging.version import Version

from spec_kitty_events.harness_observation import (
    HARNESS_OBSERVATION_PAYLOAD_IDS,
    ObservationKind,
)
from spec_kitty_events.strict import (
    _E2_STRICT_SINCE,
    STRICT_EVENT_TYPES,
    SUPPORT_MATRIX,
    SupportRow,
    support_matrix_digest,
)
from spec_kitty_events.zeitgeist_attrs import VOLATILE_EVENT_TYPES

_SCHEMA_DIR = Path(__file__).resolve().parent.parent / "src" / "spec_kitty_events" / "schemas"
_SUPPORT_MATRIX_PATH = (
    Path(__file__).resolve().parent.parent / "src" / "spec_kitty_events" / "support_matrix.json"
)
_FIXTURE_MANIFEST_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "spec_kitty_events"
    / "conformance"
    / "fixtures"
    / "manifest.json"
)

# The 30 (event_type, kind) row keys, committed in-test (draft §3.4 as
# amended by E2), mirroring
# the EXPECTED_CANONICAL_LANES pattern used elsewhere in this package.
EXPECTED_ROW_KEYS: frozenset[tuple[str, str | None]] = frozenset(
    {
        ("MissionCreated", None),
        ("MissionClosed", None),
        ("MissionStarted", None),
        ("MissionCompleted", None),
        ("MissionCancelled", None),
        ("PhaseEntered", None),
        ("ReviewRollback", None),
        ("MissionReopened", None),
        ("FollowUpRecorded", None),
        ("WPStatusChanged", None),
        ("WPCreated", None),
        ("ProjectInitialized", None),
        ("SpecifyStarted", None),
        ("SpecifyCompleted", None),
        ("PlanStarted", None),
        ("PlanCompleted", None),
        ("TasksStarted", None),
        ("TasksCompleted", None),
        ("MissionRunStarted", None),
        ("NextStepIssued", None),
        ("NextStepAutoCompleted", None),
        ("DecisionInputRequested", None),
        ("DecisionInputAnswered", None),
        ("MissionRunCompleted", None),
        ("HarnessObservation", "presence"),
        ("HarnessObservation", "lane_signal"),
        ("HarnessObservation", "focus_started"),
        ("HarnessObservation", "focus_heartbeat"),
        ("HarnessObservation", "focus_paused"),
        ("HarnessObservation", "focus_ended"),
    }
)

EXPECTED_PAYLOAD_IDS: frozenset[str] = frozenset(
    {
        "harness.presence.v1",
        "harness.lane_signal.v1",
        "harness.focus_started.v1",
        "harness.focus_heartbeat.v1",
        "harness.focus_paused.v1",
        "harness.focus_ended.v1",
    }
)

E2_MISSION_RUN_EVENT_TYPES: frozenset[str] = frozenset(
    {
        "MissionRunStarted",
        "NextStepIssued",
        "NextStepAutoCompleted",
        "DecisionInputRequested",
        "DecisionInputAnswered",
        "MissionRunCompleted",
    }
)


def test_support_matrix_has_exactly_30_rows() -> None:
    assert len(SUPPORT_MATRIX) == 30


def test_ephemeral_vocabulary_is_volatile() -> None:
    """E2: the mission/WP moment vocabulary broadcasts, it does not sync."""
    expected_volatile = {
        "WPStatusChanged",
        "MissionCreated",
        "MissionClosed",
        "PhaseEntered",
        "MissionRunStarted",
        "NextStepIssued",
        "NextStepAutoCompleted",
        "DecisionInputRequested",
        "DecisionInputAnswered",
        "MissionRunCompleted",
    }
    durability = {row.event_type: row.durability for row in SUPPORT_MATRIX}
    for event_type in expected_volatile:
        assert durability[event_type] == "volatile", event_type
    volatile_non_observation = {
        row.event_type
        for row in SUPPORT_MATRIX
        if row.durability == "volatile" and row.event_type != "HarnessObservation"
    }
    assert volatile_non_observation == expected_volatile


def test_volatile_support_matrix_rows_are_all_zeitgeist_broadcast() -> None:
    """Cross-check the two independent sources of truth directly (#23), not
    just each against its own in-test literal: a ``durability="volatile"``
    row has no durable server-side existence, so the strict profile must
    never admit one that :mod:`zeitgeist_attrs` cannot actually broadcast —
    that failure mode (a type added to ``SUPPORT_MATRIX`` as volatile but
    never wired into ``VOLATILE_EVENT_TYPES``) stayed green under the old
    per-file hardcoded-literal tests as long as each literal was kept in
    sync with its own module, even though the two modules had drifted apart.

    This is deliberately a subset, not the ``==`` the finding proposed:
    ``VOLATILE_EVENT_TYPES`` (8.2.0, #77) also covers event types that are
    durably journaled and additionally broadcast for the moment/feed
    requirements (``SpecifyStarted`` et al., still ``durability="journal"``
    here) and types not yet admitted to the strict profile at all
    (``DecisionPointOpened``/``DecisionPointResolved``) — so it is a
    superset of the volatile support-matrix rows, never a mismatch of it.
    """
    volatile_non_observation = {
        row.event_type
        for row in SUPPORT_MATRIX
        if row.durability == "volatile" and row.event_type != "HarnessObservation"
    }
    assert volatile_non_observation <= VOLATILE_EVENT_TYPES, (
        volatile_non_observation - VOLATILE_EVENT_TYPES
    )


def test_mission_run_rows_use_the_mission_next_models() -> None:
    rows = [row for row in SUPPORT_MATRIX if row.family == "mission_run"]
    assert len(rows) == 6
    for row in rows:
        assert row.model.startswith("spec_kitty_events.mission_next.")
        assert row.payload_id is None and row.kind is None


def test_mission_run_rows_pin_min_consumer_to_strict_since() -> None:
    """E2 rows must not admit strict envelopes before consumers can read them."""
    rows = [row for row in SUPPORT_MATRIX if row.family == "mission_run"]
    assert {row.event_type for row in rows} == E2_MISSION_RUN_EVENT_TYPES
    for row in rows:
        assert row.strict_since == "8.0.0", row.event_type
        assert row.min_consumer_package == row.strict_since, row.event_type


def test_mission_run_strict_since_is_pinned_to_the_e2_marker_and_postdates_introduction() -> None:
    """Pin ``_E2_STRICT_SINCE`` (strict.py) itself as the row.strict_since
    authority for the six mission_run rows (#23): each row must equal the
    module marker's value, and the marker must postdate each row's
    ``introduced_in`` — the semantics ``strict.py`` documents ("first
    strict-admitted later than their 2.3.0 introduction"). This test
    catches two gaps the pre-existing
    ``test_mission_run_rows_pin_min_consumer_to_strict_since`` misses: that
    test never checks ordering, so bumping a row's ``introduced_in`` past
    its ``strict_since`` leaves it green while this test's ``Version(...)
    >`` assertion catches it; and pinning to ``_E2_STRICT_SINCE`` directly,
    rather than the hardcoded ``"8.0.0"`` literal that other test uses,
    means a future marker bump needs no edit here, while the other test —
    in this same file, above — needs its literal updated by hand. The
    equality check is on values, not source references: it fails on drift
    (a row hardcoding a ``strict_since`` that disagrees with the marker),
    not on a row whose marker reference is swapped for an identical
    literal, and not on a marker bump with all six rows still referencing
    the marker.
    """
    rows = [row for row in SUPPORT_MATRIX if row.family == "mission_run"]
    assert len(rows) == 6
    for row in rows:
        assert row.strict_since == _E2_STRICT_SINCE, row.event_type
        assert Version(row.strict_since) > Version(row.introduced_in), row.event_type


def test_support_matrix_row_keys_match_expected() -> None:
    actual = {(row.event_type, row.kind) for row in SUPPORT_MATRIX}
    assert actual == EXPECTED_ROW_KEYS


def test_support_matrix_has_no_duplicate_row_keys() -> None:
    keys = [(row.event_type, row.kind) for row in SUPPORT_MATRIX]
    assert len(keys) == len(set(keys))


def test_support_matrix_has_exactly_six_payload_ids() -> None:
    payload_ids = {row.payload_id for row in SUPPORT_MATRIX if row.payload_id is not None}
    assert payload_ids == EXPECTED_PAYLOAD_IDS
    assert len(payload_ids) == 6
    assert payload_ids == HARNESS_OBSERVATION_PAYLOAD_IDS


def test_journal_rows_have_no_payload_id() -> None:
    for row in SUPPORT_MATRIX:
        if row.event_type != "HarnessObservation":
            assert row.payload_id is None, row.event_type
            assert row.kind is None, row.event_type


def test_observation_rows_have_a_payload_id_and_kind() -> None:
    observation_rows = [row for row in SUPPORT_MATRIX if row.event_type == "HarnessObservation"]
    assert len(observation_rows) == 6
    for row in observation_rows:
        assert row.payload_id is not None
        assert row.kind in {kind.value for kind in ObservationKind}
        assert row.payload_id == f"harness.{row.kind}.v1"


def test_every_row_event_type_is_admitted_or_harness_observation() -> None:
    for row in SUPPORT_MATRIX:
        assert row.event_type in STRICT_EVENT_TYPES


def test_every_row_is_strict() -> None:
    for row in SUPPORT_MATRIX:
        assert row.strict is True


def test_every_row_model_is_importable_and_strict() -> None:
    """Every row's ``model`` dotted path resolves to a real, frozen,
    ``extra='forbid'`` pydantic model (draft §5 Renata check (g))."""
    for row in SUPPORT_MATRIX:
        module_path, _, class_name = row.model.rpartition(".")
        assert module_path, f"{row.model!r} is not a dotted path"
        module = importlib.import_module(module_path)
        model_cls = getattr(module, class_name)
        assert model_cls.model_config.get("extra") == "forbid", row.model
        assert model_cls.model_config.get("frozen") is True, row.model


def test_every_row_schema_file_is_committed() -> None:
    for row in SUPPORT_MATRIX:
        schema_path = _SCHEMA_DIR / row.schema_
        assert schema_path.is_file(), f"{row.event_type}: missing schema {row.schema_}"


def test_support_row_rejects_unknown_extra_field() -> None:
    with pytest.raises(Exception):
        SupportRow(
            event_type="MissionCreated",
            kind=None,
            payload_id=None,
            family="lifecycle",
            durability="journal",
            model="spec_kitty_events.lifecycle.MissionCreatedPayload",
            schema="mission_created_payload.schema.json",
            strict=True,
            introduced_in="3.0.0",
            strict_since="3.0.0",
            status="supported",
            min_consumer_package="7.0.0",
            unknown_extra_field="nope",  # type: ignore[call-arg]
        )


# ---------------------------------------------------------------------------
# support_matrix_digest()
# ---------------------------------------------------------------------------


def test_support_matrix_digest_is_stable_across_two_generations() -> None:
    """C7: two generations in a clean runner produce an equal digest."""
    first = support_matrix_digest()
    second = support_matrix_digest()
    assert first == second


def test_support_matrix_digest_has_sha256_prefix() -> None:
    digest = support_matrix_digest()
    assert digest.startswith("sha256:")
    assert len(digest) == len("sha256:") + 64


# ---------------------------------------------------------------------------
# support_matrix.json (published copy, generated + drift-checked)
# ---------------------------------------------------------------------------


def test_support_matrix_json_is_committed_and_matches_generator() -> None:
    from spec_kitty_events.schemas.generate import generate_support_matrix_json

    assert _SUPPORT_MATRIX_PATH.is_file(), "support_matrix.json not generated/committed"
    expected = generate_support_matrix_json()
    actual = _SUPPORT_MATRIX_PATH.read_text(encoding="utf-8")
    assert actual == expected, "support_matrix.json is stale; run schemas/generate.py"


def test_support_matrix_json_has_30_entries() -> None:
    data = json.loads(_SUPPORT_MATRIX_PATH.read_text(encoding="utf-8"))
    assert isinstance(data, list)
    assert len(data) == 30


def test_support_matrix_json_uses_schema_key_not_schema_underscore() -> None:
    """The wire/JSON key is exactly `schema` (draft §3.4), even though the
    Python attribute is `schema_` (renamed to avoid shadowing
    `BaseModel.schema`, see strict.SupportRow docstring)."""
    data = json.loads(_SUPPORT_MATRIX_PATH.read_text(encoding="utf-8"))
    for row in data:
        assert "schema" in row
        assert "schema_" not in row


def test_e2_fixture_min_versions_match_mission_run_support_rows() -> None:
    """The E2 attrs manifest and support matrix publish one package floor."""
    manifest = json.loads(_FIXTURE_MANIFEST_PATH.read_text(encoding="utf-8"))
    strict_since_by_event_type = {
        row.event_type: row.strict_since
        for row in SUPPORT_MATRIX
        if row.event_type in E2_MISSION_RUN_EVENT_TYPES
    }
    min_consumer_by_event_type = {
        row.event_type: row.min_consumer_package
        for row in SUPPORT_MATRIX
        if row.event_type in E2_MISSION_RUN_EVENT_TYPES
    }
    checked: set[str] = set()

    for entry in manifest["fixtures"]:
        event_type = entry["event_type"]
        if event_type not in E2_MISSION_RUN_EVENT_TYPES:
            continue
        if not entry["path"].startswith("zeitgeist_attrs/"):
            continue

        checked.add(event_type)
        assert entry["min_version"] == strict_since_by_event_type[event_type]
        assert entry["min_version"] == min_consumer_by_event_type[event_type]

    assert checked == E2_MISSION_RUN_EVENT_TYPES


def test_phase_entered_ref_derivation_fixtures_share_one_min_version() -> None:
    """``phase_entered_optional_absent`` and ``phase_entered_mission_slug_absent``
    both pin the same ref-derivation fix (issue #18: ``PhaseEntered``'s frame
    ``ref`` comes from the required ``mission_id``, never the optional
    ``mission_slug`` back-compat field) and must therefore publish one
    floor. They drifted to two different, both-stale, floors (``8.0.0`` and
    ``8.1.0``) while the behaviour they describe did not actually ship until
    ``8.2.0`` (issue #72) — a consumer on either released version emitted
    the pre-fix ``ref`` and could not satisfy either fixture."""
    manifest = json.loads(_FIXTURE_MANIFEST_PATH.read_text(encoding="utf-8"))
    by_id = {entry["id"]: entry for entry in manifest["fixtures"]}
    ref_derivation_ids = {"phase_entered_optional_absent", "phase_entered_mission_slug_absent"}
    assert ref_derivation_ids <= by_id.keys()
    min_versions = {by_id[fixture_id]["min_version"] for fixture_id in ref_derivation_ids}
    assert min_versions == {"8.2.0"}


def test_mission_created_mission_id_present_fixture_pins_one_min_version() -> None:
    """``mission_created_mission_id_present`` pins the derived ``summary``
    attr, not just ``mission_id`` itself: ``mission_id`` has been in
    ``MissionCreated``'s schema-derived key set since ``8.0.0``, but no
    released codec reproduces this fixture's ``expected_attrs`` before
    ``8.2.0`` -- at ``8.0.0`` the payload does not even construct
    (``MissionCreatedPayload`` had no ``actor`` field yet) and at ``8.1.0``
    it constructs but the projection omits ``summary``, which
    ``_mission_created_summary`` only started deriving in released
    ``8.2.0``. The floor drifted to a provably-false ``8.0.0`` once already
    (spec-kitty-events#197); this pins the corrected floor across the three
    places that each independently claim it -- the manifest entry, the
    fixture's own ``notes``, and ``COMPATIBILITY.md``'s prose -- so a future
    edit to one without the other two is caught here rather than shipping
    silently green."""
    manifest = json.loads(_FIXTURE_MANIFEST_PATH.read_text(encoding="utf-8"))
    by_id = {entry["id"]: entry for entry in manifest["fixtures"]}
    entry = by_id["mission_created_mission_id_present"]
    assert entry["min_version"] == "8.2.0"

    fixture_path = _FIXTURE_MANIFEST_PATH.parent / entry["path"]
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    assert "8.2.0" in fixture["notes"]
    assert "8.0.0 first introduced the whole zeitgeist_attrs module" in fixture["notes"]

    compatibility_path = Path(__file__).resolve().parent.parent / "COMPATIBILITY.md"
    compatibility_text = compatibility_path.read_text(encoding="utf-8")
    assert "mission_created_mission_id_present` conformance fixture" in compatibility_text
    assert "min_version: 8.2.0" in compatibility_text
    assert "min_version: 8.0.0" not in compatibility_text


# ---------------------------------------------------------------------------
# V6: simulated 6.x-consumer skew (draft §4 row V6)
# ---------------------------------------------------------------------------


def test_old_consumer_fails_closed(monkeypatch: pytest.MonkeyPatch) -> None:
    """A pre-7.0 consumer that has not registered ``HarnessObservation``
    (e.g. because it monkeypatches/lacks the registry entry) gets a fail-closed
    ``ValueError`` from :func:`validate_event`, never a silent pass-through."""
    from spec_kitty_events.conformance import validators as validators_module

    monkeypatch.delitem(validators_module._EVENT_TYPE_TO_MODEL, "HarnessObservation")
    with pytest.raises(ValueError, match="Unknown event type"):
        validators_module.validate_event(
            {"kind": "presence", "harness": "claude", "session_id": "s1", "activity": "file_edit"},
            "HarnessObservation",
        )
